*----------------------------------------------------------------------*
***INCLUDE LWZ_WIZARDFCB .
*----------------------------------------------------------------------*
*&WZ_PATTERN_WIZARD_CALLBACK&
*&---------------------------------------------------------------
*&      FORM  CB_PROCESS_STEP_START
*&---------------------------------------------------------------
FORM CB_PROCESS_STEP_START                "#EC CALLED
        TABLES
           CONTAINER
        USING
           COMMAND.
* begin of local data definition
  DATA:
    L_WIZARD    type SWF_WIZARD.
* end of local data definition

* first screen (button 'back' will be automatically switched off
* and there will be NO popup 'you will lose data'...)
  l_WIZARD-SCREEN_TYP = WIZARD_SCREEN_START.

* initialize wizard step
* the wizard has one unique title while it is running
  L_WIZARD-TITLE      = TEXT-TTL.
L_WIZARD-DESCOBJECT = 'ZBDFRAMEWORKD_WIZ_FUGRUPD_001'
. "this is a text in dialog (SE61)
* call wizard screen
  CALL FUNCTION 'SWF_WIZARD_CALL'
       EXPORTING
            WIZARD_DATA                 = L_WIZARD
       EXCEPTIONS
            OPERATION_CANCELLED_BY_USER = 01
            BACK                        = 02.
  SWF_EVALUATE COMMAND.


ENDFORM.                    " CB_PROCESS_STEP_START
*&---------------------------------------------------------------
*&      FORM  CB_PROCESS_STEP_0200
*&---------------------------------------------------------------
FORM CB_PROCESS_STEP_0200                "#EC CALLED
        TABLES
           CONTAINER
        USING
           COMMAND.
* begin of local data definition
  DATA:
    L_WIZARD    type SWF_WIZARD.
* end of local data definition

* initialize wizard step
* the wizard has one unique title while it is running
  L_WIZARD-TITLE      = TEXT-TTL.
L_WIZARD-DESCOBJECT = 'ENTER NAMESPACE, DB TABLE AND TABLE TYPE'
. "this is a text in dialog (SE61)
  L_WIZARD-SUBSCREEN1 = '0200'.
  L_WIZARD-SUBSCPOOL1 = 'SAPLZBDFRAMEWORKD_WIZ_FUGRUPD'.

* set subscreen data (transport data out of global wizard data
* to global screen data )
  PERFORM USR_SET_SUBSCREEN_DATA_0200.

* call wizard screen
  CALL FUNCTION 'SWF_WIZARD_CALL'
       EXPORTING
            WIZARD_DATA                 = L_WIZARD
       EXCEPTIONS
            OPERATION_CANCELLED_BY_USER = 01
            BACK                        = 02.
  SWF_EVALUATE COMMAND.

* set subscreen data from global screen data back to the global
* wizard area
  PERFORM USR_GET_SUBSCREEN_DATA_0200.


ENDFORM.                    " CB_PROCESS_STEP_0200
*&---------------------------------------------------------------
*&      FORM  CB_PROCESS_STEP_0300
*&---------------------------------------------------------------
FORM CB_PROCESS_STEP_0300                "#EC CALLED
        TABLES
           CONTAINER
        USING
           COMMAND.
* begin of local data definition
  DATA:
    L_WIZARD    type SWF_WIZARD.
* end of local data definition

* initialize wizard step
* the wizard has one unique title while it is running
  L_WIZARD-TITLE      = TEXT-TTL.
L_WIZARD-DESCOBJECT = 'CONFIRM AUTOGENERATED NAMES'
. "this is a text in dialog (SE61)
  L_WIZARD-SUBSCREEN1 = '0300'.
  L_WIZARD-SUBSCPOOL1 = 'SAPLZBDFRAMEWORKD_WIZ_FUGRUPD'.

* set subscreen data (transport data out of global wizard data
* to global screen data )
  PERFORM USR_SET_SUBSCREEN_DATA_0300.

* call wizard screen
  CALL FUNCTION 'SWF_WIZARD_CALL'
       EXPORTING
            WIZARD_DATA                 = L_WIZARD
       EXCEPTIONS
            OPERATION_CANCELLED_BY_USER = 01
            BACK                        = 02.
  SWF_EVALUATE COMMAND.

* set subscreen data from global screen data back to the global
* wizard area
  PERFORM USR_GET_SUBSCREEN_DATA_0300.


ENDFORM.                    " CB_PROCESS_STEP_0300
*&---------------------------------------------------------------
*&      FORM  CB_PROCESS_STEP_FINISH
*&---------------------------------------------------------------
FORM CB_PROCESS_STEP_FINISH                "#EC CALLED
        TABLES
           CONTAINER
        USING
           COMMAND.
* begin of local data definition
  DATA:
    L_WIZARD    type SWF_WIZARD.
* end of local data definition

* initialize wizard step
* the wizard has one unique title while it is running
  L_WIZARD-TITLE      = TEXT-TTL.
L_WIZARD-DESCOBJECT = 'ZBDFRAMEWORKD_WIZ_FUGRUPD_007'
. "this is a text in dialog (SE61)
* last screen (button 'continue' will be called 'done')
  L_WIZARD-screen_typ = WIZARD_SCREEN_END.

* call wizard screen
  CALL FUNCTION 'SWF_WIZARD_CALL'
       EXPORTING
            WIZARD_DATA                 = L_WIZARD
       EXCEPTIONS
            OPERATION_CANCELLED_BY_USER = 01
            BACK                        = 02.
  SWF_EVALUATE COMMAND.

* process data collected by wizard
  PERFORM USR_PROCESS_WIZARD_DATA.

ENDFORM.                    " CB_PROCESS_STEP_FINISH
